"""models

Revision ID: 82529fc6d974
Revises: 56e0605a0301
Create Date: 2025-10-12 19:57:49.740784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82529fc6d974'
down_revision: Union[str, Sequence[str], None] = '56e0605a0301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('note_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notetags_table',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tagse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note_table.id'], ),
    sa.ForeignKeyConstraint(['tagse_id'], ['tags_table.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tagse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notetags_table')
    op.drop_table('note_table')
    op.drop_table('user_table')
    op.drop_table('tags_table')
    # ### end Alembic commands ###
