"""initial migration

Revision ID: 9b8fec0762a9
Revises: 
Create Date: 2025-10-11 20:00:13.089104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8fec0762a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_table')
    op.drop_table('author_book')
    op.drop_table('book_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('book_table_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('titel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='book_table_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('author_book',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_table.id'], name=op.f('author_book_book_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['author_table.id'], name=op.f('author_book_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('author_book_pkey'))
    )
    op.create_table('author_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('author_table_pkey'))
    )
    # ### end Alembic commands ###
