"""refactor SessionModel

Revision ID: 05b87568af05
Revises: 8c1cc1e70b13
Create Date: 2025-10-18 16:10:24.270479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b87568af05'
down_revision: Union[str, Sequence[str], None] = '8c1cc1e70b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ses_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ses_user', 'created_at')
    # ### end Alembic commands ###
