"""add adding fields created_at and expires_at  to SessionModel

Revision ID: 62342e0ef6da
Revises: 05b87568af05
Create Date: 2025-10-18 16:29:09.608484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62342e0ef6da'
down_revision: Union[str, Sequence[str], None] = '05b87568af05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'ses_user',
    sa.Column(
        'expires_at',
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("(NOW() + interval '24 hours')")  # PostgreSQL UTC + 24 часа
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ses_user', 'expires_at')
    # ### end Alembic commands ###
