"""add colum 'name' to table Tags

Revision ID: 70f325d21aa1
Revises: ae2524f57e47
Create Date: 2025-10-22 02:32:29.027037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f325d21aa1'
down_revision: Union[str, Sequence[str], None] = 'ae2524f57e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
