"""add colum tags to table Note

Revision ID: ced5bba72ffd
Revises: 70f325d21aa1
Create Date: 2025-10-22 03:02:59.541639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced5bba72ffd'
down_revision: Union[str, Sequence[str], None] = '70f325d21aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
