"""fixed models User, Tags, Note

Revision ID: d417dbce21e6
Revises: 62342e0ef6da
Create Date: 2025-10-20 06:18:47.155374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd417dbce21e6'
down_revision: Union[str, Sequence[str], None] = '62342e0ef6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tags', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'name')
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
